import Methods
Methods.get_contact()
Methods.get_single_contact()
Methods.making_a_payment()
Methods.create_contact()
Methods.unassigned_agreements()
Methods.direct_debit()
Methods.get_a_payment_request()
Methods.list_payments()
Methods.get_a_particular_payment()
Methods.list_payment_request()
Methods.list_all_unassigned_agreements()
Methods.single_unassigned_agreement()