import Methods
Methods.get_contact()
# Methods.get_single_contact()
# Methods.create_contact()
# Methods.unassigned_agreements()
# Methods.direct_debit()
# Methods.get_a_payment_request()
# Methods.list_payment_request()
# Methods.get_paymentrequest_history()
# Methods.list_incoming_paymentrequest()
# Methods.approve_paymentrequest() #not tested yet
# Methods.decline_paymentrequest() #not tested
# Methods.list_payments()
# Methods.get_a_particular_payment()
# Methods.making_a_payment()
# Methods.list_all_unassigned_agreements()
# Methods.single_unassigned_agreements() 
# Methods.all_bank_connections()
# Methods.one_bank_connection()
# Methods.delete_bank_connection()
# Methods.open_agreements()
# Methods.list_agreement()
# Methods.activate_closed_open_agreement()
# Methods.close_active_agreements()
# Methods.agreement_withKYC()
# Methods.receivable_contact()
# Methods.simulate_incoming_payid()